TYPO3-Documentation/TYPO3CMS-Reference-TSconfig

Documentation/UserTsconfig/Options/Index.rst
options.clearCache.clearRTECache was removed from TYPO3 CMS 6.1
with https://review.typo3.org/12912
options.clearCache.clearLangCache was removed from TYPO3 CMS 6.2
with https://review.typo3.org/24077
=> [TASK] Remove documentation for clearRTECache

Documentation/UserTsconfig/Options/Index.rst
Please do **not merge before** https://review.typo3.org/#/c/31898/ is submitted.
Thank you :)
Documents the option introduced in #50780 that allows appending
the alternative element browser mount points.
Resolves: #63009
Releases: master
Change-Id: Idbfcf6a21419716df619adb51342ac0e656c387c
=> [TASK] Document options.pageTree.altElementBrowserMountPoints.append

Documentation/PageTsconfig/Mod/Index.rst
fieldOrder was used to re-arrange specific fields in quick edit mode of the page module.
This however is mostly broken since 4.5 with all the --div-- and --palette-- containers and
only a couple of elements can be moved around successfully. This option is now removed
from documentation in 6.2 and master and will be dropped code wise in master completely.
=> [TASK] Remove mod.web_layout.tt_content.fieldOrder

Documentation/PageTsconfig/Mod/Index.rst
TCEFORM."table"."field".linkTitleToSelf can be used in FormEngine to link the
label of a single rendered field to a "sub form" of the displayed row where only
this single field is displayed. This has zero advantage usability wise.
Documentation of this feature is now removed in 6.2 and master, and it will
be dropped code wise in master completely.
=> Drop linkTitleToSelf

Documentation/PageTsconfig/Mod/Index.rst
TCEFORM."table"."field".linkTitleToSelf can be used in FormEngine to link the
label of a single rendered field to a "sub form" of the displayed row where only
this single field is displayed. This has zero advantage usability wise.
Documentation of this feature is now removed in 6.2 and master, and it will
be dropped code wise in master completely.
=> Drop linkTitleToSelf 

Documentation/PageTsconfig/Mod/Index.rst
add the description for property BackendLayouts so there is no need
to generate a database entry to define them
(Feature: #61903)
=> [TASK] description for property BackendLayouts

Documentation/UserTsconfig/Options/Index.rst
According to https://forge.typo3.org/issues/49359 the property options.moduleMenuCollapsable has been removed a lot of time ago (since 4.5 at least)
here I remove it from documentation
=> [Task] remove moduleMenuCollapsable from doc

Documentation/UserTsconfig/Options/Index.rst
Documented: 
* https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.3/Feature-73461-EnableImportModuleForNonAdminUsers.html
=> [TASK] Updated docs for TYPO3 8.3

Documentation/PageTsconfig/Mod/Index.rst
The keys of the menu items in the info module may change over time,
so the docs will not be able to provide have current examples. Explain this
and explain a better way to find out which menu items use what kind of key.
Since menu items are registered, it is easier to use the configuration module
instead of inspecting html source code.
=> Enhance description how to find out menu item keys

Documentation/UserTsconfig/Setup/Index.rst
The setting was removed years ago. See https://forge.typo3.org/issues/56479 and https://forge.typo3.org/issues/24585
=> Remove condensedMode from docs

Documentation/UserTsconfig/Options/Index.rst
They are not evaluated at last from v7.6
=> Remove unused options clickMenuTimeOut and alwaysShowClickMenuInTopFrame

Documentation/UserTsconfig/Options/Index.rst
They are not in the core (in 8.7 and 9)
=> Remove 2 unused TS settings: separateNotinmenuPages and alphasortNotinmenuPages

Documentation/UserTsconfig/Options/Index.rst
In TYPO3 v9 some PageTSConfig options were dropped.
see https://review.typo3.org/54560
=> Remove old PageTSConfig options documentation

Documentation/UserTsconfig/Options/Index.rst
Documentation about disabling items of contextmenu for pagetree now reports also the (undocumented) options added by the extension EXT:impexp.
Please review and format properly
=> document options added by impexp

Documentation/PageTsconfig/Options/Index.rst
As backendLayout's aren't not only saved in DB, the so called uid can also be a string like `pagets__Default`.
=> [TASK] Remove value type for options.backendlayout.exclude

Documentation/PageTsconfig/Mod/Index.rst
The preview is not rendered if a hook returns content
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/backend/Classes/View/PageLayoutView.php#L2155
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/Classes/Hooks/PageLayoutView/TextPreviewRenderer.php
https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/frontend/ext_localconf.php#L89
So the example with the text ce is misleading.
=> [TASK] Add note to mod.web_layout.tt_content.preview

Documentation/UserTsconfig/Options.rst, Documentation/UsingSetting/Index.rst
Do no longer provide examples where TYPO3_CONF_VARS is accessed without
$GLOBALS prefix.
Accordingly to #15 of security guide.
=> TASK: Always use GLOBALS['TYPO3_CONF_VARS']

Documentation/UserTsconfig/Options.rst
With #84749, the Duplicate Button will be hidden per default throughout
the Backend. It can be enabled globally and refined on a per table base.
=> [TASK] Document showDuplicate visibility management

Documentation/UserTsconfig/AdmPanel.rst
for admin users the admPanel is enabled by default. This information needs an higher emphasis IMHO
discard this change if you think it is no good.
=> more emphasis about enabled admPanel for admin

Documentation/UserTsconfig/AdmPanel.rst
admPanel.enable = 0
does not disable admin panel in TYPO3 9
only
admPanel.enable.all = 0
or
admPanel.hide = 1
will end in an expected result
=> Correct TS configuration example to disable admin panel for users

Documentation/UsingSetting/Index.rst
Keep reference to detail information. The removed information is already
mentioned there, in an easier to understand way.
=> TASK: Remove overcomplicated documentation part.

Documentation/UsingSetting/Index.rst
The preferred extension for PageTS files is .tsconfig, not .txt anymore.
=> Use the preferred extension for PageTS files

Documentation/PageTsconfig/TceForm.rst
as stated on this issue: https://forge.typo3.org/issues/80427#note-10 if an item has an empty value, an "odd" syntax with double dots must be used.
Please review the formatting and texting. Thanks.
=> [TASK] Document the altLabels option with empty value

Documentation/PageTsconfig/TceMain.rst
The functionality to set a custom TCEMAIN.previewDomain via PageTS was removed in TYPO3 Version 10.
See https://forge.typo3.org/issues/88499
=> [TASK] Remove TCEMAIN.previewDomain

Documentation/PageTsconfig/TceMain.rst
Document TCEMAIN.preview.disableButtonForDokType (which is there since TYPO3 7.6).
=> Document TCEMAIN.preview.disableButtonForDokType

Documentation/PageTsconfig/Mod.rst, Documentation/PageTsconfig/Options.rst, Documentation/PageTsconfig/TcaDefaults.rst, Documentation/PageTsconfig/TceForm.rst, Documentation/UserTsconfig/Options.rst, Documentation/UserTsconfig/Page.rst, Documentation/UserTsconfig/TcaDefaults.rst
Due to history indentation was used in some places.
This is rendered as block quote nowadays.
Therefore indentation is fixed when block quote is not intended.
Also some definition lists had a blank line after the definition term.
=> Fix block quotes

Documentation/PageTsconfig/TceMain.rst
If I understand the code in public/typo3/sysext/core/Classes/DataHandling/DataHandler.php:8847 right, the cache of the parent page is also cleared.
=> Clarify default cache clearing behavior when editing a page record

Documentation/PageTsconfig/Mod.rst
This is confusing and tripped me up, but for `web_layout` the actual key is `menu.functions`, for `web_info` the key is `menu_function`.
=> [TASK] Fix a spelling error

Documentation/UserTsconfig/Setup.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92560-BackendEditorsCanAlwaysDeletePagesRecursive.html
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
=> Remove User TSconfig option recursiveDelete

Documentation/UserTsconfig/Options.rst
See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Feature-92337-AllowTranslatableLabelsForBookmarkGroups.html
Related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
=> Add hint about translatable labels for bookmark groups

Documentation/PageTsconfig/Mod.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-93077-RemovedUnneededConfigurationsInPageLayoutView.html
=> [TASK] Remove disableSearchBox and disableIconToolbar

Documentation/UserTsconfig/Options.rst
See https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Breaking-92941-LockToIPUserTsConfigOptionRemoved.html 
=> [TASK] Remove options.lockToIp

Documentation/PageTsconfig/TceMain.rst
The TCEMAIN.clearCacheCmd = pages|all page TSconfig needs special permissions for non-admin users.
=> Add permission information for clearCacheCmd

Documentation/UserTsconfig/Options.rst
Updated description of where this option applies and changed some wordings.
@refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1353
=> Feature: #73176 - Filterable Trees in Record Selectors and Link Pickers

Documentation/PageTsconfig/TceForm.rst
Standardize the naming of the key of the data structure. It's always 'dataStructureKey' in the rest of the doc. (Fixes #177)
=> Fix typo 'dataStructKey' to 'dataStructureKey'

Documentation/UserTsconfig/Options.rst
As far as I understand, this setting still works in TYPO3 11.5 LTS.
It was removed in TYPO3 Version 9:
https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Breaking-82919-RemovedPageTreeRelatesTsConfigSettings.html
But it seemed to be reintroduced with this Issue?
https://forge.typo3.org/issues/87581
=> Reintroduce setting pageTree.excludeDoktypes

Documentation/PageTsconfig/TceForm.rst
TCA treeConfig.startingPoints was introduces with https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Feature-95037-NewStartingPointsSettingForFormEngineTreeConfig.html and rootUid deprecated with https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Deprecation-95037-RootUidRelatedSettingOfTrees.html Therefore I adjusted the related page TSconfig here.
releases: master, 11.5
=> Add treeConfig.startingPoints, remove rootUid

Documentation/PageTsconfig/TceMain.rst
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-89917-InheritPageAccess.html
references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1624
releases: main
=> Feature: #89917 - Copy page access settings from parent

Documentation/PageTsconfig/TceForm.rst
This has been wrongly documented. I would therefore backport this down to 9.5
solves #182
releases: master, 11.5, 10.5, 9.5
=> [BUGFIX] Update TCEFORM.<table>.<field>.disable description

Documentation/UserTsconfig/AdmPanel.rst
Those subModules do not implement the necessary Interface ConfigurableInterface and are therefore always enabled.
releases: main, 11.5, 10.4
=> [BUGFIX] Do not document enabling of admPanel submodules

Documentation/Index.rst, Documentation/Settings.cfg, README.rst
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185
=> [DOCS] Add links to further TypoScript manuals in abstract

Documentation/PageTsconfig/Mod.rst, Documentation/PageTsconfig/TceForm.rst, Documentation/UserTsconfig/Auth.rst
- fixed indenting
- removed extra newline after :aspect:`Example`
The indenting on the affected pages was also changed to use only
3 spaces indenting (as is defined in .editorconfig). There was
a mixture of 3 and 4 spaces indenting which makes it very difficult
to maintain the pages properly.
Since a lot of text was changed, it will probably not be possible
to backport, suggest to create a separate page for the other branches
or leave it be for now.
Related: TYPO3-Documentation/T3DocTeam#150
Related: TYPO3-Documentation/T3DocTeam#191
=> Fix formatting which resulted in blockquotes

Documentation/PageTsconfig/TceMain.rst
Table of contents for the properties (with the directive
"contents") and a subsection "Properties" is added.
Resolves: #249
=> Add subsection properties and local toctree to page TCEMAIN

Documentation/UserTsconfig/Options.rst
Table of contents for the properties (with the directive
"contents") and a subsection "Properties" is added.
Resolves: #249
=> Add subsection properties and local toctree to page options

Documentation/PageTsconfig/TceForm.rst
Table of contents for the properties (with the directive
"contents") and a subsection "Properties" is added.
Resolves: #249
=> Add subsection properties and local toctree to page TCEFORM

Documentation/PageTsconfig/Rte.rst
- a table of contents for the properties is added (with the directive
"content")
- and a subsection "Properties" is added
Resolves: #249
=> Add subsection properties and local toctree (to page RTE)

Documentation/UsingSetting/UserTSconfig.rst
Use spaces instead of tabs to avoid large indents. Additionally,
place code blocks correctly in the examples list.
=> [TASK] Indent code blocks correctly

Documentation/UsingSetting/PageTSconfig.rst
Important: Before merging into 11.5 and 10.4 the captions of the code blocks
have to be adjusted or removed. In 11.5 the captions are already wrong.
Resolves: #269
Releases: main, 11.5, 10.4
=> [BUGFIX] Adjust example for overriding and modifying values

Documentation/PageTsconfig/Mod.rst
This patch adds notes for options that were
removed in v12. These options were not
explicitly deprecated.
- mod.web_layout.disableNewContentElementWizard
- mod.newContentElementWizard.override
Related: TYPO3-Documentation/Changelog-To-Doc#118
=> [TASK] Add note for removed TSconfig options (branch 11.5)

Documentation/PageTsconfig/Mod.rst
Remove the following TSconfig options:
- mod.web_layout.disableNewContentElementWizard
- mod.newContentElementWizard.override
Resolves: TYPO3-Documentation/Changelog-To-Doc#118
=> [TASK] Remove TSconfig options related to new content wizard

Documentation/UserTsconfig/Options.rst
The module "func" is not available anymore and was substituted with "ts" in the example.
See: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96733-RemovedSupportForModuleHandlingBasedOnTBE_MODULES.html#migration (last line at the end)
Releases: main
=> [TASK] Adapt hideModules to the new syntax

Documentation/UserTsconfig/Options.rst
This is a follow-up to https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/commit/10fbdecd38cbfd53878a23a775df389e37bbd5e5
Releases: main
=> [TASK] Add note about changed configuration of hideModules

Documentation/UsingSetting/PageTSconfig.rst, Documentation/UsingSetting/UserTSconfig.rst
See: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html
=> [Backport 11.5] [BUGFIX] Use "TsConfig" as path part (#301)

.gitignore, composer.json
It was not possible to generate the EXT: paths for PHP files anymore, so I used the FQN class paths instead.
Added a shorthand composer command to generate the code snippets:
`ddev composer generate`
=> [Bugfix] make the screenshot tool run again with composer-installer v5

Documentation/PageTsconfig/TceMain.rst
"delete" flag (delete pages) is NOT enabled by default for groups. The doc seems a bit confusing.
See: https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/core/Classes/DataHandling/PagePermissionAssembler.php#L43
=> Remove wrong default group permission

Documentation/PageTsconfig/TceMain.rst
"delete" flag (delete pages) is not enabled by default for groups. The doc seems a bit confusing.
See: https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/core/Classes/DataHandling/PagePermissionAssembler.php#L43
=> Remove wrong default group permission (#311)

Documentation/PageTsconfig/TceMain.rst
"delete" flag (delete pages) is not enabled by default for groups. The doc seems a bit confusing. See: https://github.com/TYPO3/typo3/blob/10.4/typo3/sysext/core/Classes/DataHandling/PagePermissionAssembler.php#L43
Co-authored-by: Sergio Catalá <instruccionesaldorso@gmail.com>
=> Remove wrong default group permission (#311) (#312)

Documentation/PageTsconfig/Mod.rst
This aligns the documentation with the changelog.
https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-90461-QuickCreateContentElementsViaNewContentElementWizard.html
=> [TASK] Use true and false instead of 1 and 0

Documentation/PageTsconfig/TceMain.rst
This was only described in TYPO3 explained up until now, though it rightfully belongs here.
Must be manually backported to v11.5 as the namespace changed
=> [FEATURE] add missing linkhandler TSconfig

Documentation/PageTsconfig/TceMain.rst
This section was erroneously in f68c852518caebca0c4fc3c0f099dac10aea2398, but the feature is only present as of TYPO3 v12.0 (https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Feature-89917-InheritPageAccess.html)
=> [BUGFIX] Remove section copyFromParent

Documentation/PageTsconfig/Tsfe.rst, Documentation/Settings.cfg
Resolves: #331
Related: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2666
-----
not in commit: This will display a deprecation note in the 9.5 version with a link to the changelog. 
Am hoping for exception to rule to no longer make changes to 9.5 branch.
=> Add deprecation note for TSFE constants

Documentation/Index.rst, Documentation/Introduction/Index.rst, Documentation/UsingSetting/PageTSconfig.rst, Documentation/UsingSetting/UserTSconfig.rst
We now use the start label again to link to start pages
Related: TYPO3-Documentation/T3DocTeam#198
=> Replace links to start page (:doc: => :ref:)

Documentation/PageTsconfig/TceForm.rst
Copied from FormEngineUtility->allowOverrideMatrix property.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/207
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/381
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/391
Releases: main
=> [TASK] Add missing overwritable TCA type properties

Documentation/UsingSetting/Conditions.rst
To make more clear which functions and variables are available in TSconfig, the docs now come with an own list.
=> [TASK] Disentangle TSconfig conditions from TypoScript conditions

Documentation/PageTsconfig/Mod.rst
=> [Backport 11.5] [BUGFIX] Correct anchor for mod.web_layout.tt_content.preview (#348)

Documentation/UsingSetting/PageTSconfig.rst
Since TYPO3 v12, the file Configuation/page.tsconfig ist automatically loaded. In order to achieve this in a compatible way which works with v11 and v12 and requires not further changes when updating to v12, a section was added to main / v12 branch.
However, this is missing in v11 version (where it is even more useful) and this results in a broken link in TYPO3 Explained (see TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2784).
Resolves: TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#2784
=> Add compatibility section for using page.tsconfig to v11 as well (v11 only)

Documentation/PageTsconfig/TceMain.rst
The configuration is in the wrong place. After specifying the table, the configuration has no effect.  See https://github.com/TYPO3/typo3/blob/0113c5431ba0ff48d90c13f89c636533c9c9deed/typo3/sysext/backend/Classes/Controller/PageLayoutController.php#L613
=> [BUGFIX] Moves disableButtonForDokType configuration

Documentation/Settings.cfg
Additionally, remove the outdated t3cheatsheets reference.
Releases: 12.4
=> [TASK] Adjust links to sysext manuals for v12.4

composer.json
This avoids composer dependency conflicts.
Releases: 12.4
=> [BUGFIX] Adjust version of used EXT:examples

.github/workflows/tests.yml
- The strategy option is removed. This is superfluous as no build matrix is defined.
- The actions/checkout action is updated to version 4.
=> [CI] Streamline GitHub workflow configuration for tests

Documentation/Introduction/Index.rst, Documentation/PageTsconfig/TceMain.rst
=> [TASK] Use "TYPO3 Explained" instead of "Core API document"

Documentation/Settings.cfg, Documentation/UsingSetting/UserTSconfig.rst
Mainly:
- Adjust heading to "Setting user TSconfig" like for "Setting page TSconfig"
- Add a TOC
- Adjust wording
- Add image captions
- Add a note about Configuration module with installed lowlevel sysext
- Fix error using TCAdefaults in user TSconfig (must be prefix with "page.")
=> [TASK] Revise "Setting user TSconfig" chapter

Documentation/Introduction/Index.rst, Documentation/PageTsconfig/TceMain.rst
=> [Backport 11.5] [TASK] Use "TYPO3 Explained" instead of "Core API document" (#372)

Documentation/Settings.cfg, Documentation/UsingSetting/UserTSconfig.rst
Mainly:
- Adjust heading to "Setting user TSconfig" like for "Setting page TSconfig"
- Add a TOC
- Adjust wording
- Add image captions
- Add a note about Configuration module with installed lowlevel sysext
- Fix error using TCAdefaults in user TSconfig (must be prefix with "page.")
=> [Backport 12.4] [TASK] Revise "Setting user TSconfig" chapter (#375)

Documentation/Settings.cfg, Documentation/UsingSetting/UserTSconfig.rst
Mainly:
- Adjust heading to "Setting user TSconfig" like for "Setting page TSconfig"
- Add a TOC
- Adjust wording
- Add image captions
- Add a note about Configuration module with installed lowlevel sysext
- Fix error using TCAdefaults in user TSconfig (must be prefix with "page.")
=> [Backport 11.5] [TASK] Revise "Setting user TSconfig" chapter (#375)

Documentation/UsingSetting/UserTSconfig.rst
Additionally, fix some mistakes as drive-by.
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/646
Releases: main
=> [TASK] Reference BeforeLoadedUserTsConfigEvent in "Setting user TSconfig" chapter

Documentation/UserTsconfig/Setup.rst
I couldn't find any information on the defaults that can be defined for the core's BE modules. So I've added this example here. From that other scenarios can be easily derived.
=> [TASK] Add example for UserTS setup.default.moduleData

Documentation/PageTsconfig/TcaDefaults.rst
Through https://forge.typo3.org/issues/102239 I noticed that flexforms are an edge-case that could be clarified here. Open to feedback for changing the wording on it. :-)
=> [DOCS] Mention TCAdefaults do not apply to flexforms

Documentation/UserTsconfig/Setup.rst
Instead of referencing to a PHP file, link to the existing page "Supported languages" in TYPO3 Explained.
=> [TASK] Link supported languages page in TYPO3 Explained

Documentation/PageTsconfig/TceForm.rst, Documentation/UsingSetting/PageTSconfig.rst
On the TCEFORM page there are several examples for setting properties in Flexforms. Usually "my_ext_pi1" is given, but this should rather by "myext_pi1".
Resolves: #403
=> Use myext_pi1 instead of my_ext_pi1

Documentation/PageTsconfig/TceForm.rst, Documentation/UsingSetting/PageTSconfig.rst
On the TCEFORM page there are several examples for setting properties in Flexforms. Usually "my_ext_pi1" is given, but this should rather by "myext_pi1".
Resolves: #403
=> Use myext_pi1 instead of my_ext_pi1 (#406)

Documentation/UsingSetting/PageTSconfig.rst
This section was prematurely committed and is unncessary since there is already a description in TCEFORM for overriding FlexForm settings.
Related: #406
=> Remove section Overriding FlexForm settings

Documentation/PageTsconfig/TceForm.rst
- add section header in description on top of page, so we can link to it
- add links to general description "Applying properties to FlexForm fields"
- Use flexFieldNames with escaped dots in some examples
- Use a real example in the general section
- add description that dots in FlexForm fields must be escaped
Resolves: #404
=> Clarify overriding FlexForm in TCEFORM

Documentation/UserTsconfig/Options.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/732
Releases: main
=> [TASK] #102499 - User TSconfig setting "overridePageModule" removed

.php-cs-fixer.dist.php, Build/Scripts/validateRstFiles.php, Documentation/UsingSetting/_PhpApi/_MyBackendController.php, Documentation/UsingSetting/_PhpApi/_MyBackendLoggedInController.php, composer.json
The typo3/coding-standards package isn't compatible with Symfony 7 yet. But as this is only a proxy package for php-cs-fixer defining some rules, we can use php-cs-fixer directly.
The configuration from the TYPO3 Core is used.
See: https://github.com/TYPO3/typo3/blob/main/Build/php-cs-fixer/config.php
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/786
=> [Backport 12.4] [CI] Use php-cs-fixer directly (#420)

Documentation/PageTsconfig/Templates.rst
Additionally, fix some other spellings (page level, subtrees, subpages).
See: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/Glossary.html
=> [TASK] Fix spelling of "page TSconfig" and "user TSconfig"

Documentation/PageTsconfig/Mod.rst, Documentation/PageTsconfig/TceMain.rst, Documentation/UserTsconfig/Options.rst
This makes it easier for readers to get to the list of pre-defined doktypes.
=> [TASK] Reference "doktype" with the corresponding chapter

Documentation/PageTsconfig/Rte.rst
In the current frontend rendering, the tag `blockquote` is incorrectly output with a space `blo ckquote` due to the line break in RST format.
=> [BUGFIX] Remove superfluous blank character

Documentation/PageTsconfig/Rte.rst
The allowTags list has changed several times in the past TYPO3 versions. I have noticed the following changes since the current documented version:
TYPO3 v8.6
```
b,i,u,a,img,br,div,center,pre,font,hr,sub,sup,p,strong,em,li,ul,ol,blockquote,strike,span
```
TYPO3 v8.7 to 10.3:
```
b,i,u,a,img,br,div,center,pre,font,hr,sub,sup,p,strong,em,li,ul,ol,blockquote,strike,span,abbr,acronym,dfn
```
TYPO3 v10.4 to main:
```
b,i,u,a,img,br,div,center,pre,figure,figcaption,font,hr,sub,sup,p,strong,em,li,ul,ol,blockquote,strike,span,abbr,acronym,dfn
```
=> [TASK] Update list of allowTags

Documentation/PageTsconfig/TceForm.rst
I had a discussion with @lolli42 about this override of TCEFORM. 
Background is this core patch: https://review.typo3.org/c/Packages/TYPO3.CMS/+/83646
Also I ~~pressured~~ kindly asked @sbuerk about reproducing this and he confirmed trouble with this; effort is ongoing to see how to solve this (thanks!!).
The previously documented change of a TCEFORM like this (multiple variations so this Page TSConfig can be inserted into any TYPO3 from v8 to v13):
```
TCEFORM.tt_content.pi_flexform.login.sDEF.showForgotPassword.label = TESTLABEL
TCEFORM.tt_content.pi_flexform.login.sDEF.showForgotPassword.config.readOnly = true
TCEFORM.tt_content.pi_flexform.login.sDEF.settings\.showForgotPassword.label = TESTLABEL
TCEFORM.tt_content.pi_flexform.login.sDEF.settings\.showForgotPassword.config.readOnly = …
```
=> [TASK] Improve details of overriding TCEFORM field config

Documentation/PageTsconfig/Mod/Shared.rst
=> [TASK] Switch to confvals for mod.SHARED

Documentation/PageTsconfig/Mod/WebInfo.rst
"Page TSconfig" is a second-level backend module since v12, so this example is outdated.
=> [TASK] Remove "Disable item "Page Tsconfig" from example

Documentation/PageTsconfig/TcaDefaults.rst
=> [TASK] Correct indentation and add title to example in TcaDefaults

Documentation/PageTsconfig/Options.rst
* use confvals
No other text changes made. This is a preparation to document options.hideModules for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/3
=> [TASK] Switch to confvals for options

Documentation/PageTsconfig/Mod/WebLayout.rst, Documentation/PageTsconfig/Mod/_backendLayouts-example.tsconfig
* use confvals
* correct header levels
No other text changes made.
The page did not yet exist in 11.5
releases: main, 12.4
=> [TASK] Switch to confvals for mod.web_layout

Documentation/PageTsconfig/Mod/Shared.rst
The caption is wrong, as the example should be added to a page field according to the description and not to a file.
=> [TASK] Remove caption of code snippet

Documentation/PageTsconfig/Rte.rst
They cause warnings since the newest version of the render-guides
=> [BUGFIX] Resolve duplicate link anchors

Documentation/UsingSetting/PageTSconfig.rst
=> [TASK] Link to site sets explainaition and improve texts

Documentation/UserTsconfig/Options.rst
The allowed and properly named options are defined here: \TYPO3\CMS\Core\Resource\DuplicationBehavior and if not written properly, a warning is logged here: \TYPO3\CMS\Filelist\Controller\FileListController::getDefaultDuplicationBehaviourAction and TYPO3 falls back to it's default `cancel`.
=> [BUGFIX] Use lowercase for file_list.uploader.defaultAction

Documentation/UsingSetting/PageTSconfig.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/891
Related: #505
Releases: main
=> [BUGFIX] Correct captions in code blocks for site sets

Documentation/PageTsconfig/Mod/Wizards.rst, Documentation/PageTsconfig/Mod/_newContentElementWizard.tsconfig, Documentation/PageTsconfig/Mod/_newContentElementWizardGroup.tsconfig
This is a preparation for https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/801
Subproperties can then be linked and deprecated separately.
=> [TASK] Turn subproperties into confvals

Documentation/PageTsconfig/Mod/Wizards.rst
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/801
Releases: main
=> [FEATURE] Auto-registration of NewContentElementWizard via TCA

Documentation/PageTsconfig/Mod/WebList.rst
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/928
Releases: main
=> [FEATURE] Allow to define default search level

Documentation/UserTsconfig/Options.rst
Resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/926 Releases: main
=> [FEATURE] User TsConfig option for default resources ViewMode

Documentation/PageTsconfig/Mod/WebLayout/BackendLayout.rst, Documentation/PageTsconfig/Mod/WebLayout/_BackendLayout.tsconfig, Documentation/PageTsconfig/Mod/WebLayout/_BackendLayout.typoscript, Documentation/PageTsconfig/Mod/WebLayout/_Default.html
References: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/922
Releases: main
=> [FEATURE] #103894 - Additional properties for columns in Page Layouts

Documentation/PageTsconfig/Mod/WebLayout.rst
=> [BUGFIX] No longer refer to removed hooks for preview

Documentation/Index.rst, Documentation/Introduction/Index.rst, Documentation/UsingSetting/Conditions.rst, Documentation/UsingSetting/PageTSconfig.rst, Documentation/UsingSetting/Syntax.rst, Documentation/UsingSetting/UserTSconfig.rst
=> [BUGFIX] Fix links to former TypoScript syntax

Documentation/UsingSetting/Conditions.rst
As mentioned in https://forge.typo3.org/issues/96385 the former treeLevel started at `0` but with the change to `tree.level` this was changed to be based at `1` for root level.
The docs need to reflect this fact.
=> [TASK] Mention tree.level starting at 1 not 0
