Documentation/Conditions/Index.rst, Documentation/PageTsconfig/TCEform/Index.rst, Documentation/UserTsconfig/Options/Index.rst
Resolves: #65013
Releases: master
Change-Id: Ic274247154c3594b89c270c0fdb52110f0d567ef
=> [TASK] Proofread and move 7.1 documentation

Documentation/PageTsconfig/TopLevelObjects/Index.rst
=> [BUGFIX] TCAdefaults are also available via PageTSconfig

Documentation/PageTsconfig/Field/Index.rst
add description for static function registerPageTSConfigFile
of ExtensionManagementUtility to register a file that will be
shown in page properties
(Feature: #68315)
=> [TASK] add function registerPageTSConfigFile

Documentation/PageTsconfig/TCEmain/Index.rst
* Migrate documented new option to official reference.
* As the feature is already documented in changes of EXT:core, it should
also be available in official reference.
=> TASK: Migrate Feature: #66370 - Add flexible Preview URL configuration

Documentation/UserTsconfig/Options/Index.rst
The settings have been removed with https://forge.typo3.org/issues/77728
=> [TASK] Remove obsolete page tree and click menu settings

Documentation/UserTsconfig/Options/Index.rst
Changed in
Breaking: #78192 - Refactor click menu (context menu)
=> Update description for contextMenu.table.[table][.tree].disableItems

Documentation/PageTsconfig/Mod/Index.rst
Add documentation for `localization.enableCopy` and `localization.enableTranslate` in `web.mod_layout`.
=> [TASK] Document localization.enable{Copy,Translate}

Documentation/UserTsconfig/TopLevelObjects/Index.rst
In order to close https://forge.typo3.org/issues/81566 I added a short explanation about how to make the set of "hidden" work with the pages context menu.
=> explanation to make "hidden" work with context menu of pages

Documentation/PageTsconfig/Field/Index.rst
https://docs.typo3.org/typo3cms/TyposcriptSyntaxReference/8.7/Syntax/Includes/#best-practices
=> [TASK] Reflect best practice in registerPageTSConfigFile example

Documentation/PageTsconfig/Mod.rst, Documentation/PageTsconfig/TceForm.rst, Documentation/PageTsconfig/TceMain.rst
Add existing youtube tutorials from official TYPO3 channel to chapters.
Resolves #81
=> TASK: Include existing official youtube tutorials

Documentation/UserTsconfig/Options.rst
see https://forge.typo3.org/issues/86885. must be merged into 8-7 branch as well
Based on: PR #90
=> uploadFieldsInTopOfEB has been removed.

Documentation/PageTsconfig/Mod.rst
Only translated records in connected mode where hidden.
=> Clarify mod.web_list.hideTranslations

Documentation/PageTsconfig/TceForm.rst
Adjust indent for description after code-block to exclude description from rendered code-block
=> [TASK] Fix indent in TSconfig reference documentation

Documentation/UserTsconfig/Options.rst
Feedit tsconfig is no longer available in the core.
=> Remove feedit tsconfig

Documentation/PageTsconfig/Mod.rst
=> [TASK] Replace EXT:lang references

Documentation/PageTsconfig/TceMain.rst
See Core Feature 86365
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/849
=> [TASK] Remove "useCacheHash" from docs

Documentation/UserTsconfig/Setup.rst
=> [TASK] Remove resizeTextareas_flexible

Documentation/PageTsconfig/Mod.rst
=> [TASK] Remove disableAdvanced setting

Documentation/PageTsconfig/Mod.rst
=> [FEATURE] Add disableSysNoteButton

Documentation/Includes.txt, Documentation/Settings.cfg, Documentation/Targets.rst
Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#199
=> [TASK] Unify link targets page

Documentation/GenIndex.rst, Documentation/Includes.rst.txt, Documentation/Index.rst, Documentation/Introduction/Index.rst, Documentation/PageTsconfig/Index.rst, Documentation/PageTsconfig/Mod.rst, Documentation/PageTsconfig/Options.rst, Documentation/PageTsconfig/Rte.rst, Documentation/PageTsconfig/TcaDefaults.rst, Documentation/PageTsconfig/TceForm.rst, Documentation/PageTsconfig/TceMain.rst, Documentation/PageTsconfig/Tx.rst, Documentation/Targets.rst, Documentation/UserTsconfig/AdmPanel.rst, Documentation/UserTsconfig/Auth.rst, Documentation/UserTsconfig/Index.rst, Documentation/UserTsconfig/Options.rst, Documentation/UserTsconfig/Page.rst, Documentation/UserTsconfig/Permissions.rst, Documentation/UserTsconfig/Setup.rst, Documentation/UserTsconfig/TcaDefaults.rst, Documentation/UserTsconfig/Tx.rst, Documentation/UsingSetting/Index.rst
And Introduce index page.
Resolves #151
=> Move Includes.txt to Includes.rst.txt

Documentation/PageTsconfig/Mod.rst
See Core Feature #92942
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1303
=> [FEATURE] Add iconOverlay for content element wizard

Documentation/UserTsconfig/Auth.rst, Documentation/UserTsconfig/Setup.rst
See Core Feature #93526
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1303
=> [FEATURE] Add MFA options to TSConfig

Documentation/PageTsconfig/Mod.rst
I have fixed a few typographical errors and have rewritten a few sentences for clearer meaning.
=> Typos and language fixes

.editorconfig, Documentation/PageTsconfig/TceForm.rst, Scripts/GenerateScreenshots/Config.json, Scripts/GenerateScreenshots/CreateMappings.sh, Scripts/GenerateScreenshots/README.rst
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1353
=> [Feature] #93794 - Override TCA description with TSconfig

Documentation/UserTsconfig/Options.rst
Also use EBNF notation for table name placeholder.
=> Add example to options.disableDelete

Documentation/PageTsconfig/TceForm.rst
This option has a corresponding TCA option.
Add this reference to interlink betweem them.
=> Add reference to itemsProcFunc

Documentation/UserTsconfig/Options.rst
references https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395
=>  [FEATURE] Important: #91496 - Changes to Password Reset functionality

Documentation/UserTsconfig/Options.rst
relates https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1395
=> Deprecation: #94165 - sys_language table

Documentation/PageTsconfig/Mod.rst
references TYPO3-Documentation/TYPO3CMS-Reference-CoreApi#1395
=> [FEATURE] #94218 - Selectable columns per table in record

Documentation/PageTsconfig/TceForm.rst
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
=> [FEATURE]  #94406 - Override fileFolder TCA configuration with TSconfig

Documentation/PageTsconfig/TceMain.rst
Implement requested changes: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-TSconfig/pull/183#pullrequestreview-737008300
=> Add additional configuration info for preview

Documentation/UserTsconfig/Options.rst
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449
Core Issue: 84184
=> [FEATURE] Add file_list.displayColumnSelector 

Documentation/PageTsconfig/Mod.rst
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449 
See Core 95068
=> [TASK] Remove showClipControlPanelsDespiteOfCMlayers

Documentation/PageTsconfig/TCEmain/Index.rst
See TYPO3-Documentation/T3DocTeam#165 for details.
=> [TASK] Unify top-level domain of dummy urls

Documentation/PageTsconfig/TceMain.rst
See TYPO3-Documentation/T3DocTeam#165 for details.
=> [TASK] Replace `example.local` with `example.localhost`

.editorconfig, Documentation/Index.rst
See TYPO3-Documentation/T3DocTeam#166 for details.
=> [TASK] Unify placeholder syntax

Documentation/PageTsconfig/TceMain.rst
=> This option can be used to disable the prefix

Documentation/Includes.rst.txt, Documentation/Settings.cfg, Documentation/UserTsconfig/Options.rst, Documentation/UserTsconfig/Page.rst, Documentation/UserTsconfig/TcaDefaults.rst, Documentation/UsingSetting/Conditions.rst, Documentation/UsingSetting/Index.rst, Documentation/UsingSetting/PageTSconfig.rst, Documentation/UsingSetting/PhpApi.rst, Documentation/UsingSetting/Syntax.rst, Documentation/UsingSetting/UserTSconfig.rst
Break up long chapter in parts, suggest to use sitepackage, use wording override always (and not overwrite) make a portal page to quickly direct users.
releases: main, 11.5
=> [TASK] Restructure setting TsConfig chapters

Documentation/UsingSetting/UserTSconfig.rst
Single quotes inside single quotes must be escaped in code snippet "Adding the default User TSconfig"
=> Single quotes must be escaped

Documentation/Index.rst, Documentation/Settings.cfg, README.rst
Relates: https://github.com/TYPO3-Documentation/T3DocTeam/issues/185
=> [DOCS] Add links to further TypoScript manuals in abstract

Documentation/PageTsconfig/Mod.rst, Documentation/PageTsconfig/Options.rst, Documentation/PageTsconfig/Rte.rst, Documentation/PageTsconfig/TcaDefaults.rst, Documentation/PageTsconfig/TceForm.rst, Documentation/PageTsconfig/TceMain.rst, Documentation/UserTsconfig/AdmPanel.rst, Documentation/UserTsconfig/Auth.rst, Documentation/UserTsconfig/Options.rst, Documentation/UserTsconfig/Page.rst, Documentation/UserTsconfig/Permissions.rst, Documentation/UserTsconfig/Setup.rst, Documentation/UserTsconfig/TcaDefaults.rst, Documentation/UsingSetting/Conditions.rst, Documentation/UsingSetting/PageTSconfig.rst, Documentation/UsingSetting/UserTSconfig.rst
to make it more clear where code should go
Releases: main, 11.5, 10.4
=> [TASK] Add captions to code-blocks

Documentation/UsingSetting/PageTSconfig.rst
=> Fix syntax for backward-compat Page TSconfig import

Documentation/UsingSetting/PageTSconfig.rst
=> PageTSconfig.rst: Syntax errors, missing imports

Documentation/UserTsconfig/Setup.rst
solves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/65
=> [!!!][TASK] Remove field resizeTextareas_MaxHeight from user settings

Documentation/UsingSetting/UserTSconfig.rst
This has been fixed in main and 11.5 but not in 10.4
=> [BUGFIX] Use correct quotes for "@import"

Documentation/UserTsconfig/AdmPanel.rst
Table of contents for the properties (with the directive
"contents") and a subsection "Properties" is added.
Resolves: #249
=> Add subsection properties and local toctree to page admPanel

Documentation/PageTsconfig/Index.rst, Documentation/PageTsconfig/Templates.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/13
=> [FEATURE] #96812 - Override backend templates with TsConfig

Documentation/UserTsconfig/Options.rst
See: https://typo3.org/security/advisory/typo3-core-sa-2022-001
Releases: main, 11.5, 10.4
=> [TASK] Add new UserTS option impexp.enableExportForNonAdminUser

Documentation/PageTsconfig/Mod.rst
Related: TYPO3-Documentation/TYPO3CMS-Guide-HowToDocument#295
=> [TASK] Correct spelling of TYPO3 versions

Documentation/PageTsconfig/Rte.rst
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/159
=> [FEATURE] Set content language direction in RichText elements

Documentation/UserTsconfig/Options.rst
resolves https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/166
=> Feature: #97821 - Option to configure primary actions in File List

Documentation/Settings.cfg
=> [TASK] Remove references to the extbase book

Documentation/UsingSetting/PageTSconfig.rst, Documentation/UsingSetting/UserTSconfig.rst
See: https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/FileStructure/Configuration/TsConfig/Index.html
=> [BUGFIX] Use "TsConfig" as path part

Documentation/PageTsconfig/Mod.rst
See https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-90461-QuickCreateContentElementsViaNewContentElementWizard.html
=> [FEATURE] #90461 - Add saveAndClose option to  NewContentElementWizard

Documentation/PageTsconfig/Rte.rst, Documentation/PageTsconfig/TceMain.rst, Documentation/UserTsconfig/Options.rst
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/204
releases: main
=> Move LocalConfiguration to system/settings.php

Documentation/PageTsconfig/TceForm.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/282
Releases: main
=> [FEATURE] #99212 - Group select item in FormEngine via TSconfig

Documentation/PageTsconfig/Rte.rst
=> [TASK] Write special TypoScript Conditions in UPPERCASE

Documentation/PageTsconfig/Rte.rst
Add missing properties from https://docs.typo3.org/p/friendsoftypo3/rtehtmlarea/main/en-us/Configuration/PageTsconfig/interfaceConfiguration/Index.html
Properties tested with TYPO3 12.2
=> [TASK] Update Rte.rst (#328)

Documentation/PageTsconfig/Rte.rst
Add missing properties from https://docs.typo3.org/p/friendsoftypo3/rtehtmlarea/main/en-us/Configuration/PageTsconfig/interfaceConfiguration/Index.html
Properties tested with TYPO3 12.2
=> [Backport 11.5] [TASK] Update Rte.rst (#328) (#341)

Documentation/PageTsconfig/Mod.rst, Documentation/UserTsconfig/Options.rst, Documentation/UsingSetting/PageTSconfig.rst
This should be in line with the definition in the glossar:
https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/Glossary.html
=> [TASK] Adjust TYPO3 version numbers

Documentation/PageTsconfig/Mod.rst, Documentation/UserTsconfig/Options.rst
This should be in line with the defintion in the glossar: https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/GeneralConventions/Glossary.html
=> [Backport 11.5] [TASK] Adjust TYPO3 version numbers (#351)

Documentation/Settings.cfg, Documentation/UserTsconfig/Options.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/463
Releases: main
=> [TASK] #100658  Drop user TSconfig createFoldersInEB and folderTree.hideCreateFolder

Documentation/Settings.cfg, Documentation/UserTsconfig/Options.rst
Resolves: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/463
Releases: main
=> [TASK] #100658  Drop user TSconfig createFoldersInEB and folderTree.hideCreateFolder (#356)

Documentation/UsingSetting/PageTSconfig.rst, Documentation/UsingSetting/PhpApi.rst, Documentation/UsingSetting/Syntax.rst, Documentation/UsingSetting/UserTSconfig.rst, Documentation/UsingSetting/_PageTSconfig/_ext_localconf_page_tsconfig_v11.php, Documentation/UsingSetting/_PageTSconfig/_pages.php, Documentation/UsingSetting/_PageTSconfig/_pages_localized.php, Documentation/UsingSetting/_PhpApi/_MyBackendController.php, Documentation/UsingSetting/_PhpApi/_MyBackendLoggedInController.php, Documentation/UsingSetting/_PhpApi/_getTSConfig.php, Documentation/UsingSetting/_PhpApi/_user.tsconfig, Documentation/UsingSetting/_UserTSconfig/_ext_localconf.php
=> Overhaul setting/using tsconfig

Documentation/UsingSetting/PageTSconfig.rst
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/645
Releases: main
=> [TASK] Add reference to BeforeLoadedPageTsConfigEvent

Documentation/PageTsconfig/ColorPalettes.rst
=> [TASK] Adjust wording in introduction text of colorPalettes

Documentation/Settings.cfg
Related: https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/734
Releases: main
=> [TASK] #102440 - Merge EXT:t3editor into backend

Documentation/UserTsconfig/Options.rst
=> [TASK] Use "confval" instead of "aspect" for user TSconfig -> options

Documentation/UserTsconfig/Options.rst
=> [Backport 12.4] [TASK] Use "confval" instead of "aspect" for user TSconfig -> options (#414)

Documentation/UserTsconfig/Options.rst
=> [Backport 11.5] [TASK] Use "confval" instead of "aspect" for user TSconfig -> options (#414)

Documentation/PageTsconfig/TceForm.rst
=> [TASK] [Backport 11.5] Improve details of overriding TCEFORM field config

Documentation/PageTsconfig/Mod/WebInfo.rst
=> [TASK] Switch to confvals for mod.web_info

Documentation/PageTsconfig/Mod/WebView.rst
* use confvals
releases: main, 12.4
=> [TASK] Switch to confvals for mod.web_view

Documentation/PageTsconfig/Templates.rst, Documentation/PageTsconfig/Tx.rst
=> [TASK] Correct indentation and introduce anchors

Documentation/PageTsconfig/Mod/Wizards.rst
* use confvals
releases: main, 12.4
=> [TASK] Switch to confvals for mod.wizards

.gitignore, Makefile
Also adjust the gitignore as the newest ddev versions do not create one automatically anymore
=> [TASK] Add test-docs to make file

Documentation/PageTsconfig/Mod/WebList.rst
* use confvals
No other text changes made
releases: main, 12.4
=> [TASK] Switch to confvals for mod.web_list

Documentation/PageTsconfig/Rte.rst
=> [TASK] Switch to confvals for rte

Documentation/PageTsconfig/TceForm.rst
=> [TASK] Switch to confvals for TCEFORM

Documentation/PageTsconfig/TceMain.rst
I tried to keep this shorter by only applying syntax changes and headers for the Examples. There are some sections including the Introduction Text that need to be changed but lets do that in another PR
* use confvals
=> [TASK] Switch to confvals for TCEMAIN

Documentation/UserTsconfig/Options.rst
=> [TASK] Improve user TSconfig options

Documentation/UserTsconfig/Auth.rst
**No textchanges made** 
- introduce confvals
- introduce headers
=> [TASK] Improve user TSconfig auth

Documentation/UserTsconfig/Index.rst, Documentation/UserTsconfig/Page.rst, Documentation/UserTsconfig/Permissions.rst, Documentation/UserTsconfig/TcaDefaults.rst, Documentation/UserTsconfig/Tx.rst
=> [TASK] Improve user TSconfig

Documentation/Index.rst, Documentation/Introduction/Index.rst, Documentation/Sitemap.rst
=> [TASK] Improve General pages

Documentation/UserTsconfig/Setup.rst, Documentation/UserTsconfig/_Setup/_user-setup-default.tsconfig
**No text changes made**
- introduce confvals
- move large codesnippet to file
=> [TASK] Improve user TSconfig setup

Documentation/UsingSetting/Conditions.rst
- use confvals
- unify and improve examples (always end a condition, we are in TSconfig here)
- give titles to examples
- add todos where examples seemed strange to me
=> [TASK] Improve Condition page

Documentation/PageTsconfig/TceForm.rst
=> [BUGFIX] Resovle rendering warnings

Documentation/UsingSetting/PageTSconfig.rst
=> [FEATURE] Add Page TSconfig provider for sites and sets

Documentation/PageTsconfig/Mod/WebList.rst, Documentation/PageTsconfig/Mod/_WebList/_downloadPresets.tsconfig, Documentation/PageTsconfig/Mod/_WebList/_downloadPresetsUser.tsconfig
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/934
Releases: main
=> [FEATURE] Add record list download presets

Documentation/guides.xml
See also https://github.com/TYPO3-Documentation/render-guides/pull/745
=> [TASK] Display confvals as TSconfig in Search facets

Documentation/UserTsconfig/Options.rst
=> Use confval-menu for user TSconfig options

Documentation/Index.rst
=> [BUGFIX] Fix links to former TypoScript in 45 min

Documentation/PageTsconfig/TceForm.rst
While reading the documentation for the first time, we noticed that it might be easier to understand if it is the same structure.
=> Clarify TCEFORM structure

Documentation/Introduction/Index.rst
=> Overhaul Introduction

Documentation/UsingSetting/Syntax.rst
=> [TASK] Site settings can be used as constants in TSconfig

Documentation/PageTsconfig/Mod/WebList.rst
References https://github.com/TYPO3-Documentation/Changelog-To-Doc/issues/934
Releases: main
=> [TASK] Add link to  BeforeRecordDownloadPresetsAreDisplayedEvent
